### ISSUE TITLE
getMinBBox gives different results for a symmetric point distribution

### ISSUE THREAD

**Issue by dmattek** [caiohamamura/flightplanning-R#6]
Here's a distribution of 19 points on a hexagonal lattice:

```
x <- c(2, 2, 2, 1, 3, 1, 3, 3, 1, 3, 1, 0, 0, 0, 4, 2, 4, 4, 2)
y <- c(2, 3, 1, 1.5, 2.5, 2.5, 1.5, 0.5, 3.5, 3.5, 0.5, 3, 2, 1, 2, 4, 1, 3, 0)
```

The minimal bounding box is a rectangle:

```
> getMinBBox(cbind(x,y))
$pts
        x    y
[1,]  3.2  4.6
[2,] -0.8  2.6
[3,]  0.8 -0.6
[4,]  4.8  1.4

$width
[1] 3.577709

$height
[1] 4.472136

$angle
       y 
26.56505 
```

But when I shift the point distribution by 1, I obtain a square instead of a rectangle:

```
> getMinBBox(cbind(x+1,y+1))
$pts
     [,1] [,2]
[1,]    5    1
[2,]    5    5
[3,]    1    5
[4,]    1    1

$width
[1] 4

$height
[1] 4

$angle
[1] 90
```

Both have the same area of 16, though. Is it possible to avoid this inconsistency?

**Comment by caiohamamura** [comment]
Can you provide a full example of the two sets of `x` `y` you are using?

**Comment by dmattek** [comment]
The data required to reproduce this issue is already above. Based on personal communication with Daniel Wollschläger, the author of `getMinBBox`, the problem stems from insufficient numerical precision when calculating the area in [line 50](https://github.com/caiohamamura/flightplanning-R/blob/43883d9c95bc9f55fb2ae37501d05865cbcf28e7/R/utils.R#L50) of the function in `utils.R` :

```
 eMin  <- which.min(widths*heights)
```

This resolves the issue:

```
areas <- round(widths*heights, digits=1e-08)
eMin  <- which.min(areas)
```

I've incorporated the improved version written by Daniel in my [ARCOS package](https://github.com/dmattek/ARCOS/blob/ae9127210c22f2f75febde739cd110a2d391afbd/R/utils.R#L465).

**Comment by caiohamamura** [comment]
Thank you for noticing, I'm currently not using the area at all, so this is not too relevant for this repository. I'll schedule the update for the future.
